package com.nauhaan.skycast.domain.model

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.time.Duration
import java.time.Instant
import java.time.ZoneOffset
import kotlin.math.abs

/**
 * The Moon calculator, against independently sourced reference values.
 *
 * ## Where the expected numbers come from
 *
 * Not from this implementation. Two independent sources, because a test whose expectations were
 * generated by the code under test proves only that the code is deterministic:
 *
 * 1. **Eclipse geometry**, which pins two phase instants exactly. A solar eclipse happens at new moon
 *    and a lunar eclipse at full moon, and both are published to the second: the total solar eclipse
 *    of 12 August 2026 (greatest eclipse 17:47 UTC) and the partial lunar eclipse of 28 August 2026
 *    (greatest eclipse 04:13 UTC, full moon 04:18 UTC).
 * 2. **PyEphem**, an independent implementation of XEphem's high-precision routines, for illumination,
 *    distance and rise times, quantities no eclipse pins down.
 *
 * The Swift twin, `MoonCalculatorTests.swift`, asserts the **same values with the same tolerances**,
 * so the two platforms cannot drift apart or agree on being wrong together.
 *
 * Each tolerance is set just wide enough for the truncated series, and no wider. Reintroducing a
 * single dropped periodic term, or an inverted elongation, was checked to break these assertions.
 */
class MoonCalculatorTest {
    /** Greatest eclipse of the total solar eclipse of 12 August 2026, necessarily a new moon. */
    private val newMoonReference: Instant = Instant.parse("2026-08-12T17:47:00Z")

    /** The full moon of 28 August 2026, the night of the partial lunar eclipse. */
    private val fullMoonReference: Instant = Instant.parse("2026-08-28T04:18:00Z")

    /** The following full moon, a synodic month later. */
    private val septemberFullMoonReference: Instant = Instant.parse("2026-09-26T16:49:00Z")

    // ── Phase instants ────────────────────────────────────────────────────

    @Test
    fun `new moon of August 2026 lands on the solar eclipse`() {
        val computed = MoonCalculator.nextTime(0.0, Instant.parse("2026-08-05T00:00:00Z"))
        assertNotNull(computed)
        // Wider than the full-moon tolerance: greatest eclipse is when the shadow axis passes
        // closest to Earth's centre, a few minutes off exact ecliptic conjunction.
        assertWithin(Duration.ofMinutes(30), newMoonReference, computed!!)
    }

    @Test
    fun `both full moons of the reference pair land within six minutes`() {
        val august = MoonCalculator.nextTime(180.0, Instant.parse("2026-08-20T00:00:00Z"))
        val september = MoonCalculator.nextTime(180.0, Instant.parse("2026-09-20T00:00:00Z"))
        assertNotNull(august)
        assertNotNull(september)
        assertWithin(Duration.ofMinutes(6), fullMoonReference, august!!)
        assertWithin(Duration.ofMinutes(6), septemberFullMoonReference, september!!)
    }

    @Test
    fun `consecutive new moons are one synodic month apart`() {
        val first = MoonCalculator.nextTime(0.0, Instant.parse("2026-03-01T00:00:00Z"))!!
        val second = MoonCalculator.nextTime(0.0, first.plusSeconds(86_400))!!
        val days = Duration.between(first, second).seconds / 86_400.0
        // The real interval varies by about half a day either side of the mean, so this checks the
        // mean is right rather than that the variation is absent.
        assertTrue("interval was $days days", abs(days - MoonCalculator.SYNODIC_MONTH) < 0.7)
    }

    @Test
    fun `upcoming list is four dated phases, in order, all ahead of now`() {
        val now = Instant.parse("2026-08-18T12:00:00Z")
        val phases = MoonCalculator.upcomingPhases(now)

        assertEquals(4, phases.size)
        assertTrue(phases.all { it.instant.isAfter(now) })
        assertEquals(phases.sortedBy { it.instant }, phases)
        // All four principal phases, each exactly once: a bug returning "next full moon" twice would
        // otherwise pass everything above.
        assertEquals(
            setOf(
                MoonPhaseName.NEW,
                MoonPhaseName.FIRST_QUARTER,
                MoonPhaseName.FULL,
                MoonPhaseName.LAST_QUARTER,
            ),
            phases.map { it.name }.toSet(),
        )
    }

    // ── Illumination ──────────────────────────────────────────────────────

    @Test
    fun `illumination at the reference full moon is essentially total`() {
        val snapshot = snapshotAt(fullMoonReference)
        assertTrue(snapshot.illuminatedFraction > 0.995)
        assertEquals(MoonPhaseName.FULL, snapshot.phase)
    }

    @Test
    fun `illumination at the reference new moon is essentially nil`() {
        val snapshot = snapshotAt(newMoonReference)
        assertTrue(snapshot.illuminatedFraction < 0.005)
        assertEquals(MoonPhaseName.NEW, snapshot.phase)
    }

    @Test
    fun `illumination matches PyEphem on a mid-cycle date`() {
        // PyEphem: 28.40% on 2026-09-16 12:00 UTC. Mid-cycle is where a truncated series is least
        // forgiving, at full or new, an error in elongation barely moves the fraction at all.
        val snapshot = snapshotAt(Instant.parse("2026-09-16T12:00:00Z"))
        assertTrue(
            "was ${snapshot.illuminatedFraction * 100}%",
            abs(snapshot.illuminatedFraction * 100 - 28.40) < 1.0,
        )
    }

    @Test
    fun `waxing and waning are the right way round`() {
        // Three days after new is waxing; three days before the next new is waning. This is the
        // assertion that catches an inverted elongation, which nothing about the *fraction* would.
        val waxing = snapshotAt(newMoonReference.plusSeconds(3 * 86_400))
        val waning = snapshotAt(newMoonReference.plusSeconds(26 * 86_400))

        assertTrue(waxing.isWaxing)
        assertTrue(!waning.isWaxing)
        assertEquals(MoonPhaseName.WAXING_CRESCENT, waxing.phase)
        assertEquals(MoonPhaseName.WANING_CRESCENT, waning.phase)
    }

    @Test
    fun `named phase always agrees with the drawn illumination`() {
        // Walk a whole cycle in six-hour steps. The label and the disc are both derived from
        // elongation, so this is the guard that they can never contradict each other on screen, a
        // "Full moon" heading over a half-lit drawing is the failure it exists to prevent.
        var offset = 0L
        while (offset < (MoonCalculator.SYNODIC_MONTH * 86_400).toLong()) {
            val snapshot = snapshotAt(newMoonReference.plusSeconds(offset))
            val lit = snapshot.illuminatedFraction
            val message = "${snapshot.phase} at $lit"

            when (snapshot.phase) {
                MoonPhaseName.NEW -> assertTrue(message, lit < 0.05)
                MoonPhaseName.FULL -> assertTrue(message, lit > 0.95)
                MoonPhaseName.FIRST_QUARTER, MoonPhaseName.LAST_QUARTER ->
                    assertTrue(message, abs(lit - 0.5) < 0.1)
                MoonPhaseName.WAXING_CRESCENT, MoonPhaseName.WANING_CRESCENT ->
                    assertTrue(message, lit < 0.55)
                MoonPhaseName.WAXING_GIBBOUS, MoonPhaseName.WANING_GIBBOUS ->
                    assertTrue(message, lit > 0.45)
            }
            offset += 6 * 3_600
        }
    }

    @Test
    fun `age runs from zero at new to about fifteen days at full`() {
        assertTrue(snapshotAt(newMoonReference).ageDays < 0.1)
        val atFull = snapshotAt(fullMoonReference).ageDays
        assertTrue("was $atFull", abs(atFull - MoonCalculator.SYNODIC_MONTH / 2) < 0.5)
    }

    // ── Distance ──────────────────────────────────────────────────────────

    @Test
    fun `distance matches PyEphem near perigee`() {
        // PyEphem: 365,669 km on 2026-12-27 12:00 UTC.
        val snapshot = snapshotAt(Instant.parse("2026-12-27T12:00:00Z"))
        assertTrue("was ${snapshot.distanceKm} km", abs(snapshot.distanceKm - 365_669) < 500)
    }

    @Test
    fun `distance stays inside the Moon's actual orbit all year`() {
        // A sign error in any distance coefficient throws the result outside these bounds, which is
        // cheaper to detect than comparing 122 dates against an ephemeris.
        var day = Instant.parse("2026-01-01T00:00:00Z")
        val end = Instant.parse("2026-12-31T00:00:00Z")
        while (day.isBefore(end)) {
            val distance = snapshotAt(day).distanceKm
            assertTrue("$distance km is closer than perigee", distance > MoonSnapshot.PERIGEE_KM)
            assertTrue("$distance km is further than apogee", distance < MoonSnapshot.APOGEE_KM)
            day = day.plusSeconds(86_400)
        }
    }

    @Test
    fun `apparent size grows as the Moon comes closer`() {
        val near = snapshotAt(Instant.parse("2026-12-27T12:00:00Z"))
        val far = snapshotAt(Instant.parse("2026-08-22T04:20:00Z")) // apogee, per the eclipse page
        assertTrue(near.distanceKm < far.distanceKm)
        assertTrue(near.angularDiameterDegrees > far.angularDiameterDegrees)
        assertTrue(near.distanceFraction < far.distanceFraction)
        // Roughly half a degree, the figure every observing guide quotes.
        assertTrue(near.angularDiameterDegrees in 0.45..0.60)
    }

    // ── Distance bands ────────────────────────────────────────────────────

    @Test
    fun `distance bands split the orbit where they say they do`() {
        // Constructed directly rather than computed from a date: the point is the mapping, and waiting
        // for the Moon to actually reach the 10th percentile of its range would make this untestable.
        fun bandAt(fraction: Double): MoonDistanceBand {
            val span = MoonSnapshot.APOGEE_KM - MoonSnapshot.PERIGEE_KM
            return stubbedSnapshot(MoonSnapshot.PERIGEE_KM + span * fraction).distanceBand
        }

        assertEquals(MoonDistanceBand.VERY_CLOSE, bandAt(0.00))
        assertEquals(MoonDistanceBand.VERY_CLOSE, bandAt(0.09))
        assertEquals(MoonDistanceBand.CLOSER, bandAt(0.11))
        assertEquals(MoonDistanceBand.AVERAGE, bandAt(0.50))
        assertEquals(MoonDistanceBand.FURTHER, bandAt(0.80))
        assertEquals(MoonDistanceBand.VERY_FAR, bandAt(0.95))
    }

    // ── Moonrise and moonset ──────────────────────────────────────────────

    @Test
    fun `moonrise matches PyEphem in London and in Male`() {
        // PyEphem, 1 August 2026: London 20:47 UTC, Malé 15:27 UTC. Two very different latitudes,
        // because a latitude sign or a radians-degrees slip can still look right at one of them.
        val day = Instant.parse("2026-08-01T12:00:00Z")
        val londonRise = MoonCalculator.riseAndSet(day, LONDON_LAT, LONDON_LON, ZoneOffset.UTC).first
        val maleRise = MoonCalculator.riseAndSet(day, MALE_LAT, MALE_LON, ZoneOffset.UTC).first

        assertNotNull(londonRise)
        assertNotNull(maleRise)
        assertWithin(Duration.ofMinutes(5), Instant.parse("2026-08-01T20:47:00Z"), londonRise!!)
        assertWithin(Duration.ofMinutes(5), Instant.parse("2026-08-01T15:27:00Z"), maleRise!!)
    }

    @Test
    fun `a full moon rises as the sun sets`() {
        // The defining geometry of a full moon: opposite the Sun, so it clears the horizon as the
        // Sun drops below it. Independent of every reference value above.
        //
        // London sunset on 28 August 2026 is 19:00 UTC. An hour of tolerance covers the Moon's 5°
        // orbital inclination, which shifts the rise either side of exact opposition.
        val rise = MoonCalculator
            .riseAndSet(fullMoonReference, LONDON_LAT, LONDON_LON, ZoneOffset.UTC)
            .first
        assertNotNull(rise)
        assertWithin(Duration.ofMinutes(60), Instant.parse("2026-08-28T19:00:00Z"), rise!!)
    }

    @Test
    fun `rise is measured at the Moon's true horizon, not at zero altitude`() {
        // A direct guard on Meeus's +0.125°, which nets horizon refraction against the Moon's
        // semidiameter and parallax. Asserted here because it has to be: dropping it to 0 moves rise
        // times by only about a minute, inside the tolerance every other test above uses, so this is
        // the one place that mistake becomes visible.
        val rise = MoonCalculator
            .riseAndSet(Instant.parse("2026-08-18T12:00:00Z"), LONDON_LAT, LONDON_LON, ZoneOffset.UTC)
            .first
        assertNotNull(rise)
        val altitude = MoonCalculator.altitudeDegrees(rise!!, LONDON_LAT, LONDON_LON)
        assertTrue("altitude at rise was $altitude", abs(altitude - 0.125) < 0.01)
    }

    @Test
    fun `the Moon is above the horizon between its rise and its set`() {
        val (rise, set) = MoonCalculator.riseAndSet(
            Instant.parse("2026-08-18T12:00:00Z"),
            LONDON_LAT,
            LONDON_LON,
            ZoneOffset.UTC,
        )
        assertNotNull(rise)
        assertNotNull(set)
        assertTrue("expected a rise followed by a set", set!!.isAfter(rise!!))

        // Sampled rather than spot-checked: a rise and set found on the wrong pair of crossings would
        // satisfy the ordering above and fail here.
        val middle = rise.plusSeconds(Duration.between(rise, set).seconds / 2)
        assertTrue(MoonCalculator.altitudeDegrees(middle, LONDON_LAT, LONDON_LON) > 0)
        assertTrue(MoonCalculator.altitudeDegrees(rise.minusSeconds(1_800), LONDON_LAT, LONDON_LON) < 0)
        assertTrue(MoonCalculator.altitudeDegrees(set.plusSeconds(1_800), LONDON_LAT, LONDON_LON) < 0)
    }

    @Test
    fun `time above the horizon is a sane span, even across midnight`() {
        // The set before the rise is the previous night's moon, and a naive subtraction makes the span
        // negative. Every date in a month must come out positive and under 24 hours.
        var day = Instant.parse("2026-08-01T12:00:00Z")
        repeat(30) {
            val span = MoonCalculator
                .snapshot(day, LONDON_LAT, LONDON_LON, ZoneOffset.UTC)
                .timeAboveHorizon
            if (span != null) {
                assertTrue("negative span on $day", !span.isNegative && !span.isZero)
                assertTrue("span longer than a day on $day", span < Duration.ofDays(1))
            }
            day = day.plusSeconds(86_400)
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    /** A snapshot with everything but the distance stubbed, for testing distance-only behaviour. */
    private fun stubbedSnapshot(distanceKm: Double): MoonSnapshot = MoonSnapshot(
        instant = Instant.EPOCH,
        illuminatedFraction = 0.5,
        elongationDegrees = 90.0,
        ageDays = 7.0,
        phase = MoonPhaseName.FIRST_QUARTER,
        distanceKm = distanceKm,
        angularDiameterDegrees = 0.5,
        moonrise = null,
        moonset = null,
        upcomingPhases = emptyList(),
    )

    private fun snapshotAt(instant: Instant): MoonSnapshot =
        MoonCalculator.snapshot(instant, LONDON_LAT, LONDON_LON, ZoneOffset.UTC)

    private fun assertWithin(tolerance: Duration, expected: Instant, actual: Instant) {
        val difference = Duration.between(expected, actual).abs()
        assertTrue(
            "expected within $tolerance of $expected but was $actual (off by $difference)",
            difference <= tolerance,
        )
    }

    private companion object {
        const val LONDON_LAT = 51.5074
        const val LONDON_LON = -0.1278
        const val MALE_LAT = 4.1755
        const val MALE_LON = 73.5093
    }
}
