import Foundation
import Testing
@testable import SkyCast

/// The Moon calculator, against independently sourced reference values.
///
/// ## Where the expected numbers come from
///
/// Not from this implementation. Two independent sources, because a test whose expectations were
/// generated by the code under test proves only that the code is deterministic:
///
/// 1. **Eclipse geometry**, which pins two phase instants exactly. A solar eclipse happens at new
///    moon and a lunar eclipse at full moon, and both are published to the second: the total solar
///    eclipse of 12 August 2026 (greatest eclipse 17:47 UTC) and the partial lunar eclipse of
///    28 August 2026 (greatest eclipse 04:13 UTC, full moon 04:18 UTC).
/// 2. **PyEphem**, an independent implementation of XEphem's high-precision routines, for
///    illumination, distance and rise times, quantities no eclipse pins down.
///
/// The Kotlin twin, `MoonCalculatorTest.kt`, asserts the **same values with the same tolerances**,
/// so the two platforms cannot drift apart or agree on being wrong together.
///
/// ## On tolerances
///
/// Each is set just wide enough for the truncated series, and no wider, tight enough that a real
/// mistake fails. Reintroducing a single dropped periodic term, or `sin` for `cos` in one coefficient,
/// was checked to break these assertions.
@Suite("Moon calculator")
struct MoonCalculatorTests {
    // MARK: - Reference instants

    /// Greatest eclipse of the total solar eclipse of 12 August 2026, necessarily a new moon.
    private let newMoonReference = Self.utc(2_026, 8, 12, 17, 47)
    /// The full moon of 28 August 2026, the night of the partial lunar eclipse.
    private let fullMoonReference = Self.utc(2_026, 8, 28, 4, 18)
    /// The following full moon, a synodic month later.
    private let septemberFullMoonReference = Self.utc(2_026, 9, 26, 16, 49)

    private static let london = (latitude: 51.5074, longitude: -0.1278)
    private static let male = (latitude: 4.1755, longitude: 73.5093)

    // MARK: - Phase instants

    @Test("The new moon of August 2026 lands on the solar eclipse")
    func newMoonMatchesSolarEclipse() throws {
        let computed = try #require(
            MoonCalculator.nextTime(elongation: 0, after: Self.utc(2_026, 8, 5, 0, 0))
        )
        // Wider than the full-moon tolerance: greatest eclipse is when the shadow axis passes
        // closest to Earth's centre, a few minutes off exact ecliptic conjunction.
        #expect(abs(computed.timeIntervalSince(newMoonReference)) < 30 * 60)
    }

    @Test("Both full moons of the reference pair land within five minutes")
    func fullMoonsMatchReference() throws {
        let august = try #require(
            MoonCalculator.nextTime(elongation: 180, after: Self.utc(2_026, 8, 20, 0, 0))
        )
        let september = try #require(
            MoonCalculator.nextTime(elongation: 180, after: Self.utc(2_026, 9, 20, 0, 0))
        )
        #expect(abs(august.timeIntervalSince(fullMoonReference)) < 6 * 60)
        #expect(abs(september.timeIntervalSince(septemberFullMoonReference)) < 6 * 60)
    }

    @Test("Consecutive new moons are one synodic month apart")
    func consecutiveNewMoonsSpanASynodicMonth() throws {
        let first = try #require(MoonCalculator.nextTime(elongation: 0, after: Self.utc(2_026, 3, 1, 0, 0)))
        let second = try #require(MoonCalculator.nextTime(elongation: 0, after: first.addingTimeInterval(86_400)))
        let days = second.timeIntervalSince(first) / 86_400
        // The real interval varies by about half a day either side of the mean, so this checks the
        // mean is right rather than that the variation is absent.
        #expect(abs(days - MoonCalculator.synodicMonth) < 0.7)
    }

    @Test("The upcoming list is four dated phases, in order, all ahead of now")
    func upcomingPhasesAreOrderedAndFuture() {
        let now = Self.utc(2_026, 8, 18, 12, 0)
        let phases = MoonCalculator.upcomingPhases(after: now)

        #expect(phases.count == 4)
        #expect(phases.allSatisfy { $0.date > now })
        #expect(phases == phases.sorted { $0.date < $1.date })
        // All four principal phases, each exactly once: a bug that returned "next full moon" twice
        // would otherwise pass everything above.
        #expect(Set(phases.map(\.name)) == [.new, .firstQuarter, .full, .lastQuarter])
    }

    // MARK: - Illumination

    @Test("Illumination at the reference full moon is essentially total")
    func fullMoonIsFullyLit() {
        let snapshot = Self.snapshot(at: fullMoonReference)
        #expect(snapshot.illuminatedFraction > 0.995)
        #expect(snapshot.phase == .full)
    }

    @Test("Illumination at the reference new moon is essentially nil")
    func newMoonIsUnlit() {
        let snapshot = Self.snapshot(at: newMoonReference)
        #expect(snapshot.illuminatedFraction < 0.005)
        #expect(snapshot.phase == .new)
    }

    @Test("Illumination matches PyEphem on a mid-cycle date")
    func illuminationMatchesEphemeris() {
        // PyEphem: 28.40% on 2026-09-16 12:00 UTC. Mid-cycle is where a truncated series is least
        // forgiving, at full or new, an error in elongation barely moves the fraction at all.
        let snapshot = Self.snapshot(at: Self.utc(2_026, 9, 16, 12, 0))
        #expect(abs(snapshot.illuminatedFraction * 100 - 28.40) < 1.0)
    }

    @Test("Waxing and waning are the right way round")
    func waxingAndWaningAreCorrect() {
        // Three days after new is waxing; three days before the next new is waning. This is the
        // assertion that catches an inverted elongation, which nothing about the *fraction* would.
        let waxing = Self.snapshot(at: newMoonReference.addingTimeInterval(3 * 86_400))
        let waning = Self.snapshot(at: newMoonReference.addingTimeInterval(26 * 86_400))

        #expect(waxing.isWaxing)
        #expect(!waning.isWaxing)
        #expect(waxing.phase == .waxingCrescent)
        #expect(waning.phase == .waningCrescent)
    }

    @Test("The named phase always agrees with the drawn illumination")
    func phaseNamesAgreeWithIllumination() {
        // Walk a whole cycle in six-hour steps. The label and the disc are both derived from
        // elongation, so this is the guard that they can never contradict each other on screen,
        // a "Full moon" heading over a half-lit drawing is the failure it exists to prevent.
        var offset: Double = 0
        while offset < MoonCalculator.synodicMonth * 86_400 {
            let snapshot = Self.snapshot(at: newMoonReference.addingTimeInterval(offset))
            let percent = snapshot.illuminatedFraction

            switch snapshot.phase {
            case .new: #expect(percent < 0.05, "new moon should be dark, was \(percent)")
            case .full: #expect(percent > 0.95, "full moon should be lit, was \(percent)")
            case .firstQuarter, .lastQuarter:
                #expect(abs(percent - 0.5) < 0.1, "a quarter moon should be half lit, was \(percent)")
            case .waxingCrescent, .waningCrescent: #expect(percent < 0.55)
            case .waxingGibbous, .waningGibbous: #expect(percent > 0.45)
            }
            offset += 6 * 3_600
        }
    }

    @Test("Age runs from zero at new to about fifteen days at full")
    func ageTracksTheCycle() {
        #expect(Self.snapshot(at: newMoonReference).ageDays < 0.1)
        let atFull = Self.snapshot(at: fullMoonReference).ageDays
        #expect(abs(atFull - MoonCalculator.synodicMonth / 2) < 0.5)
    }

    // MARK: - Distance

    @Test("Distance matches PyEphem near perigee")
    func distanceMatchesEphemeris() {
        // PyEphem: 365,669 km on 2026-12-27 12:00 UTC.
        let snapshot = Self.snapshot(at: Self.utc(2_026, 12, 27, 12, 0))
        #expect(abs(snapshot.distanceKm - 365_669) < 500)
    }

    @Test("Distance stays inside the Moon's actual orbit all year")
    func distanceStaysWithinOrbit() {
        // A sign error in any distance coefficient throws the result outside these bounds, which is
        // cheaper to detect than comparing 122 dates against an ephemeris.
        var day = Self.utc(2_026, 1, 1, 0, 0)
        let end = Self.utc(2_026, 12, 31, 0, 0)
        while day < end {
            let distance = Self.snapshot(at: day).distanceKm
            #expect(distance > MoonSnapshot.perigeeKm, "\(distance) km is closer than perigee")
            #expect(distance < MoonSnapshot.apogeeKm, "\(distance) km is further than apogee")
            day = day.addingTimeInterval(86_400)
        }
    }

    @Test("Apparent size grows as the Moon comes closer")
    func angularDiameterVariesInverselyWithDistance() {
        let near = Self.snapshot(at: Self.utc(2_026, 12, 27, 12, 0))
        let far = Self.snapshot(at: Self.utc(2_026, 8, 22, 4, 20)) // apogee, per the eclipse page
        #expect(near.distanceKm < far.distanceKm)
        #expect(near.angularDiameterDegrees > far.angularDiameterDegrees)
        #expect(near.distanceFraction < far.distanceFraction)
        // Roughly half a degree, the figure every observing guide quotes.
        #expect(near.angularDiameterDegrees > 0.45 && near.angularDiameterDegrees < 0.60)
    }

    // MARK: - Distance bands

    @Test("Distance bands split the orbit where they say they do")
    func distanceBandsMapCorrectly() {
        /// Constructed directly rather than computed from a date: the point is the mapping, and waiting
        /// for the Moon to actually reach the 10th percentile of its range would make this untestable.
        func band(atFraction fraction: Double) -> MoonDistanceBand {
            let span = MoonSnapshot.apogeeKm - MoonSnapshot.perigeeKm
            return Self.snapshot(distanceKm: MoonSnapshot.perigeeKm + span * fraction).distanceBand
        }

        #expect(band(atFraction: 0.00) == .veryClose)
        #expect(band(atFraction: 0.09) == .veryClose)
        #expect(band(atFraction: 0.11) == .closer)
        #expect(band(atFraction: 0.50) == .average)
        #expect(band(atFraction: 0.80) == .further)
        // 0.80 of the range is ordinary, not remarkable.
        #expect(band(atFraction: 0.80) != .veryFar)
        #expect(band(atFraction: 0.95) == .veryFar)
    }

    // MARK: - Moonrise and moonset

    @Test("Moonrise matches PyEphem in London and in Malé")
    func moonriseMatchesEphemeris() throws {
        // PyEphem, 1 August 2026: London 20:47 UTC, Malé 15:27 UTC. Two very different latitudes,
        // because a latitude sign or a radians/degrees slip can still look right at one of them.
        let londonRise = try #require(
            MoonCalculator.riseAndSet(
                on: Self.utc(2_026, 8, 1, 12, 0),
                latitude: Self.london.latitude,
                longitude: Self.london.longitude,
                timeZone: .gmt
            ).rise
        )
        let maleRise = try #require(
            MoonCalculator.riseAndSet(
                on: Self.utc(2_026, 8, 1, 12, 0),
                latitude: Self.male.latitude,
                longitude: Self.male.longitude,
                timeZone: .gmt
            ).rise
        )
        #expect(abs(londonRise.timeIntervalSince(Self.utc(2_026, 8, 1, 20, 47))) < 5 * 60)
        #expect(abs(maleRise.timeIntervalSince(Self.utc(2_026, 8, 1, 15, 27))) < 5 * 60)
    }

    @Test("A full moon rises as the sun sets")
    func fullMoonRisesAroundSunset() throws {
        // The defining geometry of a full moon: opposite the Sun, so it clears the horizon as the
        // Sun drops below it. Independent of every reference value above.
        //
        // London sunset on 28 August 2026 is 19:00 UTC. An hour of tolerance covers the Moon's 5°
        // orbital inclination, which shifts the rise either side of exact opposition.
        let rise = try #require(
            MoonCalculator.riseAndSet(
                on: fullMoonReference,
                latitude: Self.london.latitude,
                longitude: Self.london.longitude,
                timeZone: .gmt
            ).rise
        )
        let sunset = Self.utc(2_026, 8, 28, 19, 0)
        #expect(abs(rise.timeIntervalSince(sunset)) < 60 * 60)
    }

    @Test("Rise is measured at the Moon's true horizon, not at zero altitude")
    func riseUsesTheMoonsHorizonConstant() throws {
        // A direct guard on Meeus's +0.125°, which nets horizon refraction against the Moon's
        // semidiameter and parallax. Asserted here because it has to be: dropping it to 0 moves rise
        // times by only about a minute, which sits inside the tolerance every other test above uses,
        // so this is the one place that mistake becomes visible.
        let rise = try #require(
            MoonCalculator.riseAndSet(
                on: Self.utc(2_026, 8, 18, 12, 0),
                latitude: Self.london.latitude,
                longitude: Self.london.longitude,
                timeZone: .gmt
            ).rise
        )
        #expect(abs(Self.altitude(at: rise) - 0.125) < 0.01)
    }

    @Test("The Moon is above the horizon between its rise and its set")
    func altitudeIsPositiveBetweenRiseAndSet() throws {
        let day = Self.utc(2_026, 8, 18, 12, 0)
        let (rise, set) = MoonCalculator.riseAndSet(
            on: day,
            latitude: Self.london.latitude,
            longitude: Self.london.longitude,
            timeZone: .gmt
        )
        let rose = try #require(rise)
        let setAt = try #require(set)
        #expect(setAt > rose, "expected this date to hold a rise followed by a set")

        // Sampled rather than spot-checked: the altitude must be positive throughout, and negative
        // outside. A rise and set found on the wrong pair of crossings would satisfy the ordering
        // above and fail here.
        let middle = rose.addingTimeInterval(setAt.timeIntervalSince(rose) / 2)
        #expect(Self.altitude(at: middle) > 0)
        #expect(Self.altitude(at: rose.addingTimeInterval(-30 * 60)) < 0)
        #expect(Self.altitude(at: setAt.addingTimeInterval(30 * 60)) < 0)
    }

    @Test("Time above the horizon is a sane span, even across midnight")
    func timeAboveHorizonHandlesMidnightWrap() {
        // The set before the rise is the previous night's moon, and a naive subtraction makes the
        // span negative. Every date in a month must come out positive and under 24 hours.
        var day = Self.utc(2_026, 8, 1, 12, 0)
        for _ in 0..<30 {
            let snapshot = MoonCalculator.snapshot(
                for: day,
                latitude: Self.london.latitude,
                longitude: Self.london.longitude,
                timeZone: .gmt
            )
            if let span = snapshot.timeAboveHorizon {
                #expect(span > 0, "negative span on \(day)")
                #expect(span < 86_400, "span longer than a day on \(day)")
            }
            day = day.addingTimeInterval(86_400)
        }
    }

    // MARK: - Helpers

    /// A snapshot with everything but the distance stubbed, for testing distance-only behaviour.
    private static func snapshot(distanceKm: Double) -> MoonSnapshot {
        MoonSnapshot(
            date: .now,
            illuminatedFraction: 0.5,
            elongationDegrees: 90,
            ageDays: 7,
            phase: .firstQuarter,
            distanceKm: distanceKm,
            angularDiameterDegrees: 0.5,
            moonrise: nil,
            moonset: nil,
            upcomingPhases: []
        )
    }

    private static func snapshot(at date: Date) -> MoonSnapshot {
        MoonCalculator.snapshot(
            for: date,
            latitude: london.latitude,
            longitude: london.longitude,
            timeZone: .gmt
        )
    }

    private static func altitude(at date: Date) -> Double {
        MoonCalculator.altitudeDegrees(
            at: date,
            latitude: london.latitude,
            longitude: london.longitude
        )
    }

    private static func utc(_ year: Int, _ month: Int, _ day: Int, _ hour: Int, _ minute: Int) -> Date {
        var components = DateComponents()
        components.year = year
        components.month = month
        components.day = day
        components.hour = hour
        components.minute = minute
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = .gmt
        // A nil here would mean the components themselves are invalid, a mistake in the test, not a
        // runtime condition, so failing loudly at the call site is right.
        return calendar.date(from: components) ?? .distantPast
    }
}
